### ISSUE TITLE
@ngtools/webpack support?

### ISSUE THREAD

**Issue by unsafecode** [shlomiassaf/ng-router-loader#4]
Does it work with `@ngtools/webpack`? So far I only get the following error:

`ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function`

Which actually matches with AoT rules for function exports.

Any tip or recommendation?

**Comment by shlomiassaf** [comment]
`@ngtools/webpack` comes with an internal lazy routing loader that does the same thing as `ng-router-loader`

If you compile with `@ngtools/webpack` you can't user this loader for AOT.

**Comment by unsafecode** [comment]
@shlomiassaf OK, thanks. Was asking since `@ngtools/webpack` now has issues dealing with _lazy loading_
