### ISSUE TITLE
Is it possible to load route on first redirect to that route?

### ISSUE THREAD

**Issue by alexeychikk** [shlomiassaf/ng-router-loader#5]
Hi! I have a question. 
I have configured everything according to example in the test folder. And now one of my routes is loading async successfully BUT new chunk that contains this module is loaded along with other assets. 
Is it possible to load appropriate chunk after first redirect to async route?

**Comment by shlomiassaf** [comment]
Yes, but it's not related to the loader, this is an `@angular/router` configuration

See [the docs](https://angular.io/docs/ts/latest/guide/router.html#!#preloading)

**Comment by alexeychikk** [comment]
Oh, sorry. Thank you very much :)
